package lox

const (
	String     = "STRING"
	Identifier = "IDENTIFIER"
	Number     = "NUMBER"
	EOF        = "EOF"
	None       = "none"

	And    = "AND"
	Class  = "CLASS"
	Else   = "ELSE"
	False  = "FALSE"
	For    = "FOR"
	Fun    = "FUN"
	If     = "IF"
	Init   = "init"
	Nil    = "NIL"
	Or     = "OR"
	Return = "RETURN"
	Super  = "SUPER"
	This   = "THIS"
	True   = "TRUE"
	Var    = "VAR"
	While  = "WHILE"

	EqualEqual   = "EQUAL_EQUAL"
	BangEqual    = "BANG_EQUAL"
	GreaterEqual = "GREATER_EQUAL"
	LessEqual    = "LESS_EQUAL"
	Greater      = "GREATER"
	Less         = "LESS"
	Bang         = "BANG"
	Equal        = "EQUAL"
	Semicolon    = "SEMICOLON"
	LeftParen    = "LEFT_PAREN"
	RightParen   = "RIGHT_PAREN"
	LeftBracket  = "LEFT_BRACKET"
	RightBracket = "RIGHT_BRACKET"
	LeftBrace    = "LEFT_BRACE"
	RightBrace   = "RIGHT_BRACE"
	Star         = "STAR"
	Dot          = "DOT"
	Comma        = "COMMA"
	Plus         = "PLUS"
	Minus        = "MINUS"
	Slash        = "SLASH"
)
