package lox

const (
	STRING     = "STRING"
	IDENTIFIER = "IDENTIFIER"
	NUMBER     = "NUMBER"
	EOF        = "EOF"
	NULL       = "null"

	AND    = "AND"
	CLASS  = "CLASS"
	ELSE   = "ELSE"
	FALSE  = "FALSE"
	FOR    = "FOR"
	FUN    = "FUN"
	IF     = "IF"
	NIL    = "NIL"
	OR     = "OR"
	RETURN = "RETURN"
	SUPER  = "SUPER"
	THIS   = "THIS"
	TRUE   = "TRUE"
	VAR    = "VAR"
	WHILE  = "WHILE"

	EQUAL_EQUAL   = "EQUAL_EQUAL"
	BANG_EQUAL    = "BANG_EQUAL"
	GREATER_EQUAL = "GREATER_EQUAL"
	LESS_EQUAL    = "LESS_EQUAL"
	GREATER       = "GREATER"
	LESS          = "LESS"
	BANG          = "BANG"
	EQUAL         = "EQUAL"
	SEMICOLON     = "SEMICOLON"
	LEFT_PAREN    = "LEFT_PAREN"
	RIGHT_PAREN   = "RIGHT_PAREN"
	LEFT_BRACE    = "LEFT_BRACE"
	RIGHT_BRACE   = "RIGHT_BRACE"
	STAR          = "STAR"
	DOT           = "DOT"
	COMMA         = "COMMA"
	PLUS          = "PLUS"
	MINUS         = "MINUS"
	SLASH         = "SLASH"
)
